version: '3'

services:
  redis:
    image: redis
    environment:
     REDIS_HOST: "127.0.0.1"
     REDIS_PORT: 6379
  web:
    depends_on:
       - redis
    build: .
    ports:
      - "5000:8080"
    environment:
     REDIS_HOST: "127.0.0.1"
     REDIS_PORT: 6379
