version: '3'

services:
  redis:
    image: redis
    ports: 
     - "6379:6379"
    volumes:
     - /var/data:/data
  web:
    image: docker-test-compose
    depends_on:
       - redis
    ports:
      - "5000:8080"
    environment:
     REDIS_HOST: redis
     REDIS_PORT: 6379
