#Creating a deployment of redis:alpine
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: node-redis
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: node-redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
        #  Our redis storage to store data
        volumeMounts:
        - name: redis-storage
          mountPath: /data
          readOnly: false
      restartPolicy: Always
      # Linking a persistentVolumeClaim
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-storage
