# Service for the web app 
apiVersion: v1
kind: Service
metadata:
  name: devops-app-service # Creating a service for both deployment 
  labels:
    app: devops-app-service
    service: devops-app-service
spec:
  ports:
   - port: 3000
     name: http # Precising the type of protocol : http for port 80
  selector:
    app: devops-project-app