# Service for the web app 
apiVersion: v1
kind: Service
metadata:
  name: devops-app-service
  labels:
    app: devops-app-service
    service: devops-app-service
spec:
  ports:
   - port: 3000
     name: http
  selector:
    app: devops-project-app