# Service for the web app 
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devops-app-service-v1
  name: devops-app-service-v1
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: devops-project-app-v1
  type: LoadBalancer
---
# Service for the web app 
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devops-app-service-v2
  name: devops-app-service-v2
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: devops-project-app-v2
  type: LoadBalancer