---
- hosts: project
  # Run commands as root
  become: true
 
  tasks: 
  - name: printf 
    command: ls
    register: command_output
  
  - name: Install npm
    yum:
      name:
        - nodejs
      state: latest

  - name: Install wget
    yum:
      name:
        - wget

  - name: Install tar
    yum:
      name:
        - tar

  - name: Install make
    yum:
      name:
        - make

  - name: wget redis
    command: wget http://download.redis.io/redis-stable.tar.gz

  - name: tar redis
    command: tar xvzf redis-stable.tar.gz

  - name: make redis
    command: cd redis-stable

  - name: make redis
    command: make

  - name: make redis
    command: cd ../

  - name: start redis
    command: redis-server

  - name: Install app
    command: npm install
    args:
      chdir: /srv/userapi


  - name: start app
    command: npm start
    args:
      chdir: /srv/userapi

  - debug:
           var: command_output.stdout_lines