---
- hosts: project
  # Run commands as root
  become: true
 
  tasks: 

  
  - name: Install npm
    apt:
      name:
        - nodejs
      state: latest

  - name: Install wget
    apt:
      name:
        - wget

  - name: Install tar
    apt:
      name:
        - tar

  - name: Install make
    apt:
      name:
        - make

  - name: wget redis
    command: wget http://download.redis.io/redis-stable.tar.gz

  - name: tar redis
    command: tar xvzf redis-stable.tar.gz

  - name: printf 
    command: ls
    register: command_output
  - debug:
           var: command_output.stdout_lines
  #- name: cd redis-stabe
  #  command: cd redis-stable

  - name: make redis
    command: make
    args:
      chdir: redis-stable

  #- name: go back 
  #  command: cd ../
  - name: printf 
    command: ls
    args:
      chdir: redis-stable/src
    register: command_output

  - debug:
           var: command_output.stdout_lines

  - name: start redis
    command: redis-server
    args:
      chdir: redis-stable/src

  - name: Install app
    command: npm install
    args:
      chdir: /srv/userapi


  - name: start app
    command: npm start
    args:
      chdir: /srv/userapi
