apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: devops-app-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  # HTTP exposing port 80 (default)
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - '*'
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: devops-app-destination
spec:
  host: devops-app-service
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: devops-app-vsc
spec:
  hosts:
  - '*'
  gateways:
  - devops-app-gateway
  http:
  - match:
    - uri:
        exact: "/"
    route:
    - destination:
        host: devops-app-service
        subset: v1
        port:
          number: 3000
      weight: 80
    - destination:
        host: devops-app-service
        subset: v2
        port:
          number: 3000
      weight: 20


