name: Redis with docker and tests
on: 
   - push
   - pull_request

jobs:
  # Label of the runner job
  runner-job:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest

    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: userapi/package.json
        # Install dependencies of the project
      - name: Install dependencies
        run: npm i
        working-directory: userapi
        
      - name: Connect to Redis
        env:
          # The hostname used to communicate with the Redis service container
          REDIS_HOST: localhost
          # The default Redis port
          REDIS_PORT: 6379
          
      - name : Building if it exists
        run: npm run build --if-present
        working-directory: userapi
        
      - name : Run tests locally
        run: npm test
        working-directory: userapi
