name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        redis-version: [4, 5, 6]

    steps:
      - uses: actions/checkout@v2
        with: 
            repository: 'kellianoy/devopslabs'
            
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Start Redis ${{ matrix.redis-version }}
        uses: ./.github/actions/dockertest@v1
        with:
          redis-version: ${{ matrix.redis-version }}
          
      - name: Install dependencies
        run: npm install
        
      - name: Run build if there's one
        run: npm run build --if-present
        
      - name: Run tests
        run: npm test    
